// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByJ-p-GEQvgLzQIN_IP6k9W4GHES7c4bw',
    appId: '1:38635906681:web:7517f5520afd2cab7756a8',
    messagingSenderId: '38635906681',
    projectId: 'kojiq3-a0dbd',
    authDomain: 'kojiq3-a0dbd.firebaseapp.com',
    storageBucket: 'kojiq3-a0dbd.appspot.com',
    measurementId: 'G-M3ZFMLGH69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnvt3Yf0ZG0B2_W6ZLMg9ZP0jY1W1rhDo',
    appId: '1:38635906681:android:61d3b91dcd6d1dfa7756a8',
    messagingSenderId: '38635906681',
    projectId: 'kojiq3-a0dbd',
    storageBucket: 'kojiq3-a0dbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv0Bvl5Uz7tCaLLpfCp9K-nAGF84vkUTg',
    appId: '1:38635906681:ios:c555079d129fbad67756a8',
    messagingSenderId: '38635906681',
    projectId: 'kojiq3-a0dbd',
    storageBucket: 'kojiq3-a0dbd.appspot.com',
    iosBundleId: 'com.example.kojiq3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv0Bvl5Uz7tCaLLpfCp9K-nAGF84vkUTg',
    appId: '1:38635906681:ios:2ef8b6ebe12668b77756a8',
    messagingSenderId: '38635906681',
    projectId: 'kojiq3-a0dbd',
    storageBucket: 'kojiq3-a0dbd.appspot.com',
    iosBundleId: 'com.example.kojiq3.RunnerTests',
  );
}
